- name: install nessesary packages
  hosts: azure
  roles:
    - common
    - docker
    - kubernetes
    - zsh

- name: install wireguard
  hosts: azure
  roles:
    - wireguard-client

- name: setup agent
  hosts: azure
  roles:
    - azure-agent