# - name: install nessesary packages
#   hosts: azure
#   roles:
#     - common
#     - docker
#     - kubernetes
#     - zsh

# - name: install wireguard
#   hosts: azure
#   roles:
#     - wireguard-client

- name: install microk8s
  hosts: azure
  roles:
    - microk8s

# - name: setup agent
#   hosts: azure
#   roles:
#     - azure-agent