---

# - name: install docker, docker compose to all
#   hosts: aws
#   roles:
#     - docker
- name: install common
  hosts: all
  roles:
    - common

    
- name: install kubernetes tools
  hosts: aws
  roles:
    - zsh