---
- name: ubuntu
  block:
    - name: instll wireguard-tools 
      apt:
        name: wireguard-tools
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: install resolvconf
      become: yes
      become_method: sudo
      apt:
        name: resolvconf
        state: present
        update_cache: yes
  when: ansible_distribution == 'Ubuntu'

