---
- name: check agent directory existed
  stat: 
    path: "{{ ansible_env.HOME }}/{{ agent_name }}/*.sh"
  register: agent_dir

- name: create agent directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ agent_name }}"
    state: directory
    mode: '0777'
  when: not agent_dir.stat.exists

- name: check_binary_existed
  stat: 
    path: /tmp/vsts-agent-linux.tar.gz
  register: binary_check

- name: download file
  command: curl https://vstsagentpackage.azureedge.net/agent/{{ azure_version }}/vsts-agent-linux-x64-{{ azure_version }}.tar.gz --output /tmp/vsts-agent-linux.tar.gz
  when: not binary_check.stat.exists

- name: tar
  command: chdir="{{ ansible_env.HOME }}/{{ agent_name }}" tar zxvf /tmp/vsts-agent-linux.tar.gz
  when: not agent_dir.stat.exists

- name: config agent
  ignore_errors: yes
  command: chdir="{{ ansible_env.HOME }}/{{ agent_name }}" ./config.sh  --unattended --url {{ azure_host }} --auth pat --token {{ azure_pat_token }} --pool {{ agent_pool }} --agent {{ agent_name }} --acceptTeeEula --sslskipcertvalidation

- name: uninstall agent
  command: chdir="{{ ansible_env.HOME }}/{{ agent_name }}" ./svc.sh uninstall
  become: true
  become_method: sudo
  ignore_errors: yes
  when: agent_dir.stat.exists

- name: install agent
  command: chdir="{{ ansible_env.HOME }}/{{ agent_name }}" ./svc.sh install
  become: true
  ignore_errors: yes
  become_method: sudo

- name: run agent
  command: chdir="{{ ansible_env.HOME }}/{{ agent_name }}" ./svc.sh start
  become: true
  become_method: sudo 