
---
- name: check install existed
  stat:
    path: /tmp/node_installer.sh
  register: node_installer
  
- name: download installer
  command: curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh -o /tmp/node_installer.sh
  register: install_node_installer
  failed_when: install_node_installer.rc != 0
  when:  not node_installer.stat.exists

- name: run installer
  command: bash /tmp/node_installer.sh