
---
- name: check install existed
  command: stat /tmp/node_installer.sh
  register: is_installer_existed
  ignore_errors: true
  no_log: true
  failed_when: is_installer_existed.rc != 0
  
- name: download installer
  command: curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh -o /tmp/node_installer.sh
  register: install_node_installer
  failed_when: install_node_installer.rc != 0
  when:  is_installer_existed.failed == true

- name: run installer
  command: bash /tmp/node_installer.sh