---
- name: check node {{ node_version }} existed
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use {{ node_version }}"
  register: node_version_check
  failed_when: node_version_check.rc != 0
  args:
    executable: /bin/bash
- name: install node {{ node_version }}
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ node_version }}"
  when: node_version_check.failed 
  args:
    executable: /bin/bash
- name: set node {{ node_version }} as default
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm alias default {{ node_version }}"
  when: node_version_check.failed
  args:
    executable: /bin/bash