---

- name: check if zsh existed
  stat:
    path: /usr/bin/zsh
  register: zsh_check

- name: install zsh
  when: not zsh_check.stat.exists
  block:
    - name: install zsh Amazon
      when: ansible_distribution == "Amazon"
      yum:
        name: zsh
        state: present
      become: true
      become_method: sudo
    - name: install zsh Ubuntu
      when: ansible_distribution == "Ubuntu"
      become: true
      become_method: sudo
      apt:
        name: zsh
        state: present
    - name: set zsh as default shell
      become: true
      become_method: sudo
      command: chsh -s /bin/zsh {{ ansible_env.USER }}
- name: check oh-my-zsh
  stat:
    path: /home/{{ ansible_user }}/.oh-my-zsh
  register: oh_my_zsh_check

- name: install oh-my-zsh
  when: not oh_my_zsh_check.stat.exists
  block:
    - name: check if ohmyzsh installer existed
      stat:
        path: /tmp/ohmyzsh_installer.sh
      register: ohmyzsh_check
    - name: download ohmyzsh installer
      when: not ohmyzsh_check.stat.exists
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh_installer.sh
        mode: 0755
    - name: install ohmyzsh
      command: /tmp/ohmyzsh_installer.sh
      become: yes
      become_method: sudo
- name: install ohmyzsh plugins
  git:
    repo: https://github.com/zsh-users/{{ item }}.git 
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/{{ item }}
    depth: 1
  with_items: "{{ zsh_plugins }}"
  ignore_errors: true

- name: get zshrc
  get_url:
    url: "{{ zshrc_url }}"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644


