---

- name: check if faas-cli existed
  command: which faas-cli
  register: faas_cli_check
  no_log: true
  ignore_errors: true
  failed_when: faas_cli_check.rc != 0

- name: check if faas-cli installer existed
  stat:
    path: /tmp/faas-cli.sh
  register: faas_cli_installer_check
  when: faas_cli_check.failed

- name: download faas-cli installer
  when: faas_cli_check.failed and not faas_cli_installer_check.stat.exists
  command: curl -L -o /tmp/faas-cli.sh https://cli.openfaas.com

- name: install faas-cli
  command: bash /tmp/faas-cli.sh
  when: faas_cli_check.failed
  become: true
  become_method: sudo