---
- when: hostvars[inventory_hostname].ansible_distribution == "Amazon"
  include_tasks: install_docker_distro_amz.yml
- when: hostvars[inventory_hostname].ansible_distribution != "Amazon"
  include_tasks: install_docker_common.yml